version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: newsfeed-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: newsfeed