version: '3.8'

services:
  newsfeedapp:
    build:
      context: .
    depends_on:
      - postgres
    container_name: newsfeed-app
    image: newsfeed:v1
    restart: no
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/newsfeed
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate

  postgres:
    image: postgres:latest
    container_name: newsfeed-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: newsfeed