-- liquibase formatted sql

-- changeset oalekseenko:1
CREATE TABLE categories (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR UNIQUE NOT NULL
);
CREATE TABLE news_articles (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   content TEXT NOT NULL,
   published_at date NOT NULL,
   category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE
);